export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_RECOMMENDS = 'FETCH_RECOMMENDS';
export const FETCH_RECOMMENDS_SUCCESS = 'FETCH_RECOMMENDS_SUCCESS';
export const FETCH_RECOMMENDS_FAILURE = 'FETCH_RECOMMENDS_FAILURE';
